In [ ]:
from google.colab import drive

drive.mount("/content/gdrive")

Mounted at /content/gdrive



#q1

In [ ]:
import pandas

df = pandas.read_csv('/content/gdrive/MyDrive/Colab Notebooks/sim/features.csv')
# df = df.drop(columns=['Unnamed: 0'])
df
y = df['price_vnd']
df = df.drop(['price_vnd'], axis='columns')
X = df.loc[:, df.columns != 'sim_number']

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error
import math
model = DecisionTreeRegressor()
model.fit(X_train, y_train)
yhat = model.predict(X_test)
mse = math.sqrt(mean_squared_error(y_test, yhat))
print('MSE: %.3f' % mse)

mae = mean_absolute_error(y_test, yhat)
print('MAE: %.3f' % mae)

In [ ]:
import pandas

df = pandas.read_csv('/content/gdrive/MyDrive/Colab Notebooks/sim/features.csv')
# df = df.drop(columns=['Unnamed: 0'])
df

price_vnd  sim_number  090  091  092  093  094  096  097  098  ...  \
0          450000   343189288    0    0    0    0    0    0    0    0  ...   
1         3000000   888899580    0    0    0    0    0    0    0    0  ...   
2          500000   928960006    0    0    1    0    0    0    0    0  ...   
3         5000000   902438679    1    0    0    0    0    0    0    0  ...   
4          450000   334307889    0    0    0    0    0    0    0    0  ...   
...           ...         ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
199995     450000   866161769    0    0    0    0    0    0    0    0  ...   
199996    1000000   708124126    0    0    0    0    0    0    0    0  ...   
199997    1000000   904755200    1    0    0    0    0    0    0    0  ...   
199998     450000   329220204    0    0    0    0    0    0    0    0  ...   
199999    1000000   904760321    1    0    0    0    0    0    0    0  ...   

        9900  9911  9922  9933  9944  9955  9966  9977  9988  9999.2  
0          0     0     0     0     0     0     0     0     0       0  
1          0     0     0     0     0     0     0     0     0       0  
2          0     0     0     0     0     0     0     0     0       0  
3          0     0     0     0     0     0     0     0     0       0  
4          0     0     0     0     0     0     0     0     0       0  
...      ...   ...   ...   ...   ...   ...   ...   ...   ...     ...  
199995     0     0     0     0     0     0     0     0     0       0  
199996     0     0     0     0     0     0     0     0     0       0  
199997     0     0     0     0     0     0     0     0     0       0  
199998     0     0     0     0     0     0     0     0     0       0  
199999     0     0     0     0     0     0     0     0     0       0  

[200000 rows x 1376 columns]

In [ ]:
y = df['price_vnd']
df = df.drop(['price_vnd'], axis='columns')
X = df.loc[:, df.columns != 'sim_number']

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
# from sklearn.preprocessing import StandardScaler
# y = df['price_vnd']
# sc_y = StandardScaler()
# y = sc_y.fit_transform(y.values.reshape(-1, 1))

# df = df.drop(['price_vnd'], axis='columns')
# X = df.loc[:, df.columns != 'sim_number']
# print(X.shape, y.shape)

In [ ]:
# from sklearn.model_selection import train_test_split
# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
# from sklearn.ensemble import RandomForestRegressor
# from sklearn.metrics import mean_absolute_error
# from sklearn.svm import SVR
# model = SVR(kernel = 'rbf')
# import xgboost as xg
# xgb_r = xg.XGBRegressor(objective ='reg:linear',
#                   n_estimators = 10, seed = 42)
 
# Fitting the model
# xgb_r.fit(X_train, y_train)
 
# Predict the model
# yhat = xgb_r.predict(X_test)

# model = RandomForestRegressor(random_state=42)
# model.fit(X_train, y_train)
# # # make predictions
# yhat = model.predict(X_test)

In [ ]:
# from sklearn.metrics import mean_squared_error
# import math
# # mae = mean_absolute_error(sc_y.inverse_transform(y_test), sc_y.inverse_transform(yhat.reshape(-1, 1)))
# # print('MAE: %.3f' % mae)
# # mse = mean_squared_error(sc_y.inverse_transform(y_test), sc_y.inverse_transform(yhat.reshape(-1, 1)))
# # print('MSE: %.3f' % mse)

# # mae = mean_absolute_error(y_test, yhat)
# # print('MAE: %.3f' % mae)
# mse = math.sqrt(mean_squared_error(y_test, yhat))
# print('MSE: %.3f' % mse)

In [ ]:
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import mean_squared_error
import math
model = DecisionTreeRegressor()
model.fit(X_train, y_train)
yhat = model.predict(X_test)
mse = math.sqrt(mean_squared_error(y_test, yhat))
print('MSE: %.3f' % mse)

mae = mean_absolute_error(y_test, yhat)
print('MAE: %.3f' % mae)

MSE: 848873191.668


In [ ]:
cnt = 0
a =  sc_y.inverse_transform(yhat.reshape(-1, 1))
b = sc_y.inverse_transform(y_test)
for i in range(len(a)):
    if a[i]/b[i] > 0.85 and a[i]/b[i] < 1.15:
        cnt += 1
print(cnt / len(a))

0.04397487150199886


#BNN

In [ ]:
import pandas
import numpy as np

df = pandas.read_csv('/content/gdrive/MyDrive/Colab Notebooks/sim/train_dataset.csv')

df['price_vnd']  = df['price_vnd']/1000
df['price_vnd'] = df['price_vnd'].astype(int)
df['sim_number'] = df['sim_number'].astype(str)
df 

price_vnd sim_number  label
0             450  343189288      1
1            3000  888899580      4
2             500  928960006      3
3            5000  902438679      5
4             450  334307889      1
...           ...        ...    ...
199995        450  866161769      1
199996       1000  708124126      2
199997       1000  904755200      2
199998        450  329220204      1
199999       1000  904760321      2

[200000 rows x 3 columns]

In [ ]:
from collections import Counter
w = Counter(df['price_vnd'])
w.most_common()

[(450, 45119),
 (1000, 38472),
 (500, 30619),
 (3000, 29199),
 (5000, 21383),
 (10000, 6139),
 (12000, 5125),
 (11325, 2682),
 (11000, 1760),
 (13000, 1720),
 (15000, 1417),
 (14000, 808),
 (50000, 786),
 (12500, 534),
 (10500, 531),
 (13500, 430),
 (55000, 429),
 (60000, 388),
 (10300, 331),
 (11500, 329),
 (65000, 302),
 (13900, 272),
 (68000, 270),
 (70000, 236),
 (12900, 236),
 (10400, 199),
 (11900, 197),
 (80000, 191),
 (79000, 184),
 (99000, 183),
 (100000, 182),
 (12600, 173),
 (11700, 171),
 (150000, 171),
 (75000, 169),
 (12800, 152),
 (120000, 149),
 (10100, 147),
 (58000, 146),
 (69000, 143),
 (59000, 142),
 (399, 138),
 (10800, 134),
 (90000, 132),
 (13125, 127),
 (95000, 120),
 (110000, 117),
 (85000, 112),
 (88000, 107),
 (13600, 104),
 (12400, 104),
 (10600, 101),
 (139000, 92),
 (299, 91),
 (11300, 86),
 (10900, 86),
 (13800, 85),
 (250000, 85),
 (52000, 82),
 (800000, 81),
 (89000, 77),
 (168000, 74),
 (10200, 73),
 (11250, 72),
 (66000, 71),
 (200000, 68),
 (11600, 6

In [ ]:
sorted(w.items())

In [ ]:
df[df['price_vnd'] <= 10000].count() - df[df['price_vnd'] < 10000].count()

price_vnd     6139
sim_number    6139
label         6139
dtype: int64

In [ ]:
df[df['price_vnd'] <= 500].count()

price_vnd     76162
sim_number    76162
label         76162
dtype: int64

In [ ]:
df[df['price_vnd'] <= 1000].count() - df[df['price_vnd'] <= 500].count()

price_vnd     38472
sim_number    38472
label         38472
dtype: int64

In [ ]:
df[df['price_vnd'] <= 3000].count() - df[df['price_vnd'] <= 1000].count()

price_vnd     29199
sim_number    29199
label         29199
dtype: int64

In [ ]:
df[df['price_vnd'] <= 5000].count() - df[df['price_vnd'] <= 3000].count()

price_vnd     21383
sim_number    21383
label         21383
dtype: int64

In [ ]:
df[df['price_vnd'] <= 10000].count() - df[df['price_vnd'] <= 5000].count()

price_vnd     6139
sim_number    6139
label         6139
dtype: int64

In [ ]:
df[df['price_vnd'] <= 30000].count() - df[df['price_vnd'] <= 10000].count()

price_vnd     19891
sim_number    19891
label         19891
dtype: int64

In [ ]:
df[df['price_vnd'] <= 100000].count() - df[df['price_vnd'] <= 30000].count()

price_vnd     5579
sim_number    5579
label         5579
dtype: int64

In [ ]:
df[df['price_vnd'] > 100000].count()

price_vnd     3175
sim_number    3175
label         3175
dtype: int64

In [ ]:
# y = df['price_vnd']
# X = df.loc[:, df.columns != 'sim_number']

# from sklearn.model_selection import train_test_split
# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
import numpy as np

X = []
for i in df['sim_number']:
  b = np.zeros(shape=(9, 10))
  de = 0
  for p in i: 
    a = np.zeros(shape=(10))
    a[int(p)] = 1
    b[de] = a 
    de += 1
  X.append(b)

In [ ]:
X = np.array(X)

In [ ]:
from sklearn.preprocessing import StandardScaler
y = df['price_vnd']
y = np.array(y)
# sc_y = StandardScaler()
# y = sc_y.fit_transform(y.values.reshape(-1, 1))

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
y_train = np.concatenate(y_train)
y_test = np.concatenate(y_test)

In [ ]:
print(X_test.shape, y_train.shape)

(40000, 9, 10) (160000,)


In [ ]:
X_train = X_train.reshape(160000,9,10,1)
X_test = X_test.reshape(40000,9,10,1)

In [ ]:
from keras.models import Sequential
from keras.layers import Dense, Conv2D, Flatten
from tensorflow.keras.optimizers import Adam

model = Sequential()

#add model layers
model.add(Conv2D(8, kernel_size=3, activation='relu', input_shape=(9,10,1)))
model.add(Conv2D(4, kernel_size=3, activation='relu'))
model.add(Flatten())
model.add(Dense(1, activation='linear'))
model.compile(loss='mse', 
    optimizer=Adam(learning_rate=0.1), 
    metrics='mse')

In [ ]:
model.fit(X_train, y_train,validation_data=(X_test, y_test), epochs=2)

Epoch 1/2
5000/5000 [==============================] - 17s 3ms/step - loss: 257921066821746688.0000 - mse: 257921066821746688.0000 - val_loss: 716053442895806464.0000 - val_mse: 716053442895806464.0000
Epoch 2/2
5000/5000 [==============================] - 17s 3ms/step - loss: 257844925641523200.0000 - mse: 257844925641523200.0000 - val_loss: 716014272794066944.0000 - val_mse: 716014272794066944.0000


In [ ]:
yhat = model.predict(X_test[64].reshape(1,9,10,1))
yhat

1/1 [==============================] - 0s 104ms/step


array([[-432813.56]], dtype=float32)

In [ ]:
yhat

array([[-432813.56]], dtype=float32)

In [ ]:
a = sc_y.inverse_transform(yhat.reshape(-1, 1))
a = a.ravel()
a

array([4329.08], dtype=float32)

In [ ]:
y_test[64]

450000

In [ ]:
 sc_y.inverse_transform(y_test[1265].reshape(-1, 1)).ravel()

array([450.])

In [ ]:
from keras.layers import Dense, Flatten
from keras.models import Sequential
from keras import metrics 
from tensorflow.keras.optimizers import Adam
# 2. buid model 
model = Sequential()
model.add(Flatten(input_shape=(9, 10)))
model.add(Dense(16, activation='relu'))
model.add(Dense(32, activation='relu'))
model.add(Dense(64, activation='relu'))
model.add(Dense(1, input_shape = (1,), activation='linear'))

# 3. loss, metrics 
model.compile(loss='mse', 
    optimizer=Adam(learning_rate=0.1), 
    metrics='mse')

In [ ]:
model.fit(X_train, y_train,validation_data=(X_test, y_test), epochs=5)

Epoch 1/5
5000/5000 [==============================] - 18s 3ms/step - loss: 256824630390554624.0000 - mse: 256824630390554624.0000 - val_loss: 715705378746138624.0000 - val_mse: 715705378746138624.0000
Epoch 2/5
5000/5000 [==============================] - 13s 3ms/step - loss: 252021465384222720.0000 - mse: 252021465384222720.0000 - val_loss: 716144702360911872.0000 - val_mse: 716144702360911872.0000
Epoch 3/5
5000/5000 [==============================] - 13s 3ms/step - loss: 245756104531771392.0000 - mse: 245756104531771392.0000 - val_loss: 717791976937750528.0000 - val_mse: 717791976937750528.0000
Epoch 4/5
5000/5000 [==============================] - 14s 3ms/step - loss: 238751373649248256.0000 - mse: 238751373649248256.0000 - val_loss: 718781125085888512.0000 - val_mse: 718781125085888512.0000
Epoch 5/5
5000/5000 [==============================] - 13s 3ms/step - loss: 227414360794857472.0000 - mse: 227414360794857472.0000 - val_loss: 720070646066839552.0000 - val_mse: 72007064606683

In [ ]:
model.predict(X_test[64].reshape(1,9,10))

1/1 [==============================] - 0s 161ms/step


array([[8939599.]], dtype=float32)

In [ ]:
from tensorflow import keras
from tensorflow.keras import layers
batch_size = 16
# Each MNIST image batch is a tensor of shape (batch_size, 28, 28).
# Each input sequence will be of size (28, 28) (height is treated like time).
input_dim = 10

units = 16
output_size = 10  # labels are from 0 to 9

# Build the RNN model
def build_model(allow_cudnn_kernel=True):
    # CuDNN is only available at the layer level, and not at the cell level.
    # This means `LSTM(units)` will use the CuDNN kernel,
    # while RNN(LSTMCell(units)) will run on non-CuDNN kernel.
    if allow_cudnn_kernel:
        # The LSTM layer with default options uses CuDNN.
        lstm_layer = keras.layers.LSTM(units, input_shape=(None, input_dim))
    else:
        # Wrapping a LSTMCell in a RNN layer will not use CuDNN.
        lstm_layer = keras.layers.RNN(
            keras.layers.LSTMCell(units), input_shape=(None, input_dim)
        )
    model = keras.models.Sequential(
        [
            lstm_layer,
            keras.layers.BatchNormalization(),
            keras.layers.Dense(1, activation='linear'),
         
        ]
    )
    return model


In [ ]:
from tensorflow.keras.optimizers import Adam
model = build_model(allow_cudnn_kernel=False)

model.compile(loss='mse', 
    optimizer=Adam(learning_rate=0.1), 
    metrics='mse')


model.fit(X_train, y_train,validation_data=(X_test, y_test), epochs=2)

Epoch 1/2
5000/5000 [==============================] - 26s 5ms/step - loss: 258170655961251840.0000 - mse: 258170655961251840.0000 - val_loss: 716423565997506560.0000 - val_mse: 716423565997506560.0000
Epoch 2/2
5000/5000 [==============================] - 25s 5ms/step - loss: 258155331517939712.0000 - mse: 258155331517939712.0000 - val_loss: 716409615943729152.0000 - val_mse: 716409615943729152.0000


In [ ]:
X_train.shape

(160000, 9, 10)

#NewFeature

In [ ]:
import pandas
import numpy as np

df = pandas.read_csv('/content/gdrive/MyDrive/Colab Notebooks/sim/train_dataset.csv')

# df['price_vnd']  = df['price_vnd']/1000
df['price_vnd'] = df['price_vnd'].astype(int)
df['sim_number'] = df['sim_number'].astype(str)
df.head()

price_vnd sim_number
0     450000  343189288
1    3000000  888899580
2     500000  928960006
3    5000000  902438679
4     450000  334307889

In [ ]:
label = []
for i in df['price_vnd']:
  if i <= 450000:
    label.append(0)
  elif i <= 500000:
    label.append(1)
  elif i <= 1000000:
    label.append(2)
  elif i <= 3000000:
    label.append(3)
  elif i <= 5000000:
    label.append(4)
  elif i <= 15000000:
    label.append(5)
  else:
    label.append(6)

In [ ]:
from collections import Counter
Counter(label)

Counter({0: 45543, 3: 29199, 1: 30619, 4: 21383, 5: 26030, 6: 8754, 2: 38472})

In [ ]:
df['class'] = label
df.head()

price_vnd sim_number  class
0     450000  343189288      0
1    3000000  888899580      3
2     500000  928960006      1
3    5000000  902438679      4
4     450000  334307889      0

In [ ]:
import numpy as np

X = []
for i in df['sim_number']:
  b = np.zeros(shape=(9, 10))
  de = 0
  for p in i: 
    a = np.zeros(shape=(10))
    a[int(p)] = 1
    b[de] = a 
    de += 1
  X.append(b)

In [ ]:
X = np.array(X)
y = df['class']
y = np.array(y)
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
X_train

array([[[0., 0., 0., ..., 0., 0., 1.],
        [1., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 1., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 1.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 1.]],

       [[0., 0., 0., ..., 0., 0., 1.],
        [0., 0., 0., ..., 0., 1., 0.],
        [0., 0., 0., ..., 0., 1., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 1., 0., 0.],
        [0., 0., 0., ..., 1., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 1., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 1.],
        ...,
        [0., 1., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 1., 0.],
        [0., 0., 0., ..., 0., 1., 0.]],

       ...,

       [[0., 0., 0., ..., 0., 0., 1.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 1., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 1., 0.],
        [0., 0., 0., ..., 0., 0., 1.],
        [0., 1., 0., ..., 0., 0.

In [ ]:
X_train.shape

(160000, 9, 10)

In [ ]:
y_test.shape

(40000,)

In [ ]:
x_train = np.reshape(X_train,[-1, 9, 10])
x_test = np.reshape(X_test,[-1, 9, 10])
x_train = X_train.astype('float32')
x_test = X_test.astype('float32')

In [ ]:
num_labels = len(np.unique(y_train))
num_labels

8

In [ ]:
y_test[0]

0

In [ ]:
y_train[0]

4

In [ ]:
from keras.utils import to_categorical
y_train = to_categorical(y_train)
y_test = to_categorical(y_test)

#RNN

In [ ]:
import keras
from keras.models import Sequential
from keras.layers import Dense, Activation, SimpleRNN


input_shape = (9, 10)
batch_size = 64
units = 128
dropout = 0.2

model = Sequential()
model.add(SimpleRNN(units=units,
                    input_shape=input_shape))
model.add(keras.layers.Dropout(0.2))
# model.add(SimpleRNN(units=64))
# model.add(keras.layers.Dense(64, activation='relu'))
# model.add(keras.layers.Dropout(0.2))
model.add(Dense(num_labels))
model.add(Activation('softmax'))
model.summary()

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 simple_rnn_6 (SimpleRNN)    (None, 128)               17792     
                                                                 
 dropout_2 (Dropout)         (None, 128)               0         
                                                                 
 dense_1 (Dense)             (None, 6)                 774       
                                                                 
 activation_1 (Activation)   (None, 6)                 0         
                                                                 
Total params: 18,566
Trainable params: 18,566
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model.compile(loss='categorical_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])
# train the network
model.fit(x_train, y_train, validation_data=(x_test, y_test), epochs=30, batch_size=batch_size)

Epoch 1/30
2500/2500 [==============================] - 14s 5ms/step - loss: 1.1706 - accuracy: 0.5583 - val_loss: 1.0822 - val_accuracy: 0.5937
Epoch 2/30
2500/2500 [==============================] - 13s 5ms/step - loss: 1.0672 - accuracy: 0.5940 - val_loss: 1.0147 - val_accuracy: 0.6153
Epoch 3/30
2500/2500 [==============================] - 13s 5ms/step - loss: 1.0212 - accuracy: 0.6095 - val_loss: 0.9816 - val_accuracy: 0.6240
Epoch 4/30
2500/2500 [==============================] - 13s 5ms/step - loss: 0.9863 - accuracy: 0.6220 - val_loss: 0.9529 - val_accuracy: 0.6354
Epoch 5/30
2500/2500 [==============================] - 13s 5ms/step - loss: 0.9583 - accuracy: 0.6317 - val_loss: 0.9336 - val_accuracy: 0.6421
Epoch 6/30
2500/2500 [==============================] - 13s 5ms/step - loss: 0.9352 - accuracy: 0.6402 - val_loss: 0.9054 - val_accuracy: 0.6534
Epoch 7/30
2500/2500 [==============================] - 12s 5ms/step - loss: 0.9169 - accuracy: 0.6466 - val_loss: 0.8915 - val_ac

In [ ]:
X_train.shape[1:]

(9, 10)

#a

In [ ]:
import keras
from keras.layers import LSTM, Bidirectional

model = keras.models.Sequential()

# model.add(keras.layers.LSTM(128, input_shape=(X_train.shape[1:]), return_sequences=True))
model.add(Bidirectional(LSTM(128, return_sequences=True), input_shape=(X_train.shape[1:])))
# model.add(Attention(units=128))
model.add(keras.layers.Dropout(0.2))
# model.add(keras.layers.LSTM(128))
model.add(Bidirectional(LSTM(128)))
model.add(keras.layers.Dense(64, activation='relu'))
model.add(keras.layers.Dropout(0.2))
model.add(keras.layers.Dense(32, activation='relu'))
model.add(keras.layers.Dropout(0.2))
model.add(keras.layers.Dense(8, activation='softmax'))

#Compiling the model
model.compile( loss='sparse_categorical_crossentropy', optimizer = keras.optimizers.Adam(learning_rate=0.001, decay=1e-6), metrics=['accuracy'] )
import tensorflow as tf
callback = tf.keras.callbacks.EarlyStopping(monitor='val_accuracy', patience=20, mode = 'max', verbose = 1)
history = model.fit(X_train, y_train, epochs=100, validation_data=(X_test, y_test), callbacks=[callback])

Epoch 1/100
5000/5000 [==============================] - 63s 12ms/step - loss: 1.1783 - accuracy: 0.5621 - val_loss: 1.0025 - val_accuracy: 0.6204
Epoch 2/100
5000/5000 [==============================] - 53s 11ms/step - loss: 0.9646 - accuracy: 0.6378 - val_loss: 0.8829 - val_accuracy: 0.6672
Epoch 3/100
5000/5000 [==============================] - 53s 11ms/step - loss: 0.8725 - accuracy: 0.6709 - val_loss: 0.8305 - val_accuracy: 0.6874
Epoch 4/100
5000/5000 [==============================] - 52s 10ms/step - loss: 0.8058 - accuracy: 0.6942 - val_loss: 0.7782 - val_accuracy: 0.7071
Epoch 5/100
5000/5000 [==============================] - 53s 11ms/step - loss: 0.7521 - accuracy: 0.7127 - val_loss: 0.7488 - val_accuracy: 0.7130
Epoch 6/100
 786/5000 [===>..........................] - ETA: 40s - loss: 0.7168 - accuracy: 0.7260

In [ ]:
a = model.predict(X_test.reshape(-1,9,10))

1250/1250 [==============================] - 7s 5ms/step


In [ ]:
a

array([[9.99996781e-01, 3.16619048e-06, 3.09144212e-08, 5.76050707e-10,
        3.78999696e-12, 2.14534938e-15],
       [9.98979270e-01, 8.04272422e-04, 1.80935574e-04, 3.52015268e-05,
        2.36667475e-07, 7.94233429e-12],
       [9.76515189e-03, 1.59254260e-02, 2.09216192e-01, 6.86319053e-01,
        7.63596296e-02, 2.41459440e-03],
       ...,
       [5.58318794e-01, 4.21119124e-01, 1.26616163e-02, 1.51582400e-03,
        6.06492115e-03, 3.19650571e-04],
       [3.25390249e-02, 9.63104010e-01, 4.22488572e-03, 6.56707707e-05,
        6.63824903e-05, 3.09065462e-09],
       [3.16821797e-07, 9.99999404e-01, 5.27020099e-08, 2.15588543e-07,
        2.83457924e-09, 1.10618645e-20]], dtype=float32)

#perceptron

In [ ]:
from keras.layers import Dense, Flatten
from keras.models import Sequential
from keras import metrics 
# 2. buid model 
model = Sequential()
model.add(Flatten(input_shape=(9, 10)))
model.add(Dense(32, activation='relu'))
model.add(Dense(64, activation='relu'))
# model.add(Dense(128, activation='relu'))
model.add(Dense(num_labels, activation='softmax'))

# 3. loss, metrics 
model.compile(loss='categorical_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])
model.fit(X_train, y_train, validation_data=(X_test, y_test), epochs=30)

Epoch 1/30
5000/5000 [==============================] - 22s 4ms/step - loss: 1.0888 - accuracy: 0.5860 - val_loss: 0.9721 - val_accuracy: 0.6284
Epoch 2/30
5000/5000 [==============================] - 15s 3ms/step - loss: 0.9376 - accuracy: 0.6395 - val_loss: 0.9083 - val_accuracy: 0.6503
Epoch 3/30
5000/5000 [==============================] - 14s 3ms/step - loss: 0.8942 - accuracy: 0.6547 - val_loss: 0.8820 - val_accuracy: 0.6607
Epoch 4/30
5000/5000 [==============================] - 13s 3ms/step - loss: 0.8704 - accuracy: 0.6637 - val_loss: 0.8648 - val_accuracy: 0.6660
Epoch 5/30
5000/5000 [==============================] - 14s 3ms/step - loss: 0.8545 - accuracy: 0.6691 - val_loss: 0.8524 - val_accuracy: 0.6713
Epoch 6/30
5000/5000 [==============================] - 14s 3ms/step - loss: 0.8417 - accuracy: 0.6730 - val_loss: 0.8466 - val_accuracy: 0.6701
Epoch 7/30
5000/5000 [==============================] - 13s 3ms/step - loss: 0.8314 - accuracy: 0.6772 - val_loss: 0.8341 - val_ac

#b


In [ ]:
from tensorflow import keras
from keras.models import Model
from keras.layers import LSTM, Bidirectional, Conv1D, MaxPooling1D, BatchNormalization, Input, Dense, Dropout, Flatten

input_layer = Input(shape=(9, 10))
conv1 = Conv1D(64, 2, activation='relu', padding='same')(input_layer)
conv2 = Conv1D(128, 2, activation='relu', padding='same')(conv1)
x = BatchNormalization()(conv2)
x = MaxPooling1D(2)(x)

lstm1 = Bidirectional(LSTM(200, return_sequences=True), 
                             input_shape=(x.shape[1:]))(x)
x = Dropout(0.2)(lstm1)

lstm2 = Bidirectional(LSTM(200))(x)
x = Dropout(0.2)(lstm2)

output_layer = Dense(7, activation='softmax')(x)
model = Model(inputs=input_layer, outputs=output_layer)
model.compile( loss='sparse_categorical_crossentropy', optimizer = keras.optimizers.Adam(), metrics=['accuracy'] )
model.summary()

Model: "model_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_4 (InputLayer)        [(None, 9, 10)]           0         
                                                                 
 conv1d_6 (Conv1D)           (None, 9, 64)             1344      
                                                                 
 conv1d_7 (Conv1D)           (None, 9, 128)            16512     
                                                                 
 batch_normalization_3 (Batc  (None, 9, 128)           512       
 hNormalization)                                                 
                                                                 
 max_pooling1d_3 (MaxPooling  (None, 4, 128)           0         
 1D)                                                             
                                                                 
 bidirectional_6 (Bidirectio  (None, 4, 400)           5264

In [ ]:
import tensorflow as tf
BATCH_SIZE = 32
EPOCHS = 200
callback = tf.keras.callbacks.EarlyStopping(monitor='val_accuracy', patience=10, mode = 'max', verbose = 1)
# model_save = tf.keras.callbacks.ModelCheckpoint('model.h5', save_best_only=True, monitor='val_accuracy', mode='max', verbose=1)
history = model.fit(X_train, y_train, batch_size=BATCH_SIZE, epochs=EPOCHS, validation_data=(X_test, y_test), callbacks=[callback])

Epoch 1/200
5000/5000 [==============================] - 63s 12ms/step - loss: 0.8970 - accuracy: 0.6591 - val_loss: 0.7527 - val_accuracy: 0.7146
Epoch 2/200
5000/5000 [==============================] - 57s 11ms/step - loss: 0.6870 - accuracy: 0.7358 - val_loss: 0.6522 - val_accuracy: 0.7494
Epoch 3/200
5000/5000 [==============================] - 57s 11ms/step - loss: 0.6045 - accuracy: 0.7665 - val_loss: 0.6172 - val_accuracy: 0.7634
Epoch 4/200
5000/5000 [==============================] - 62s 12ms/step - loss: 0.5448 - accuracy: 0.7895 - val_loss: 0.5961 - val_accuracy: 0.7728
Epoch 5/200
5000/5000 [==============================] - 56s 11ms/step - loss: 0.4961 - accuracy: 0.8078 - val_loss: 0.5944 - val_accuracy: 0.7761
Epoch 6/200
5000/5000 [==============================] - 56s 11ms/step - loss: 0.4551 - accuracy: 0.8230 - val_loss: 0.6028 - val_accuracy: 0.7774
Epoch 7/200
5000/5000 [==============================] - 57s 11ms/step - loss: 0.4177 - accuracy: 0.8379 - val_loss: 0

In [ ]:
print(model.summary())

Model: "sequential_7"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv1d_21 (Conv1D)          (None, 9, 32)             672       
                                                                 
 batch_normalization_21 (Bat  (None, 9, 32)            128       
 chNormalization)                                                
                                                                 
 conv1d_22 (Conv1D)          (None, 9, 64)             4160      
                                                                 
 batch_normalization_22 (Bat  (None, 9, 64)            256       
 chNormalization)                                                
                                                                 
 conv1d_23 (Conv1D)          (None, 9, 128)            16512     
                                                                 
 batch_normalization_23 (Bat  (None, 9, 128)          

In [ ]:
aa = model.predict(X_test)
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
y_pred = np.argmax(aa, axis=1)
print(classification_report(y_test,y_pred))

1250/1250 [==============================] - 8s 5ms/step
              precision    recall  f1-score   support

           0       0.90      0.95      0.92      9136
           1       0.77      0.79      0.78      6083
           2       0.86      0.78      0.82      7665
           3       0.61      0.65      0.63      5915
           4       0.55      0.48      0.52      4187
           5       0.75      0.79      0.77      5250
           6       0.96      0.84      0.89      1764

    accuracy                           0.78     40000
   macro avg       0.77      0.76      0.76     40000
weighted avg       0.78      0.78      0.77     40000



              precision    recall  f1-score   support

           0       0.90      0.94      0.92      9136
           1       0.79      0.76      0.78      6083
           2       0.82      0.81      0.81      7665
           3       0.61      0.63      0.62      5915
           4       0.52      0.49      0.51      4187
           5       0.76      0.76      0.76      5250
           6       0.91      0.86      0.89      1764

    accuracy                           0.77     40000
   macro avg       0.76      0.75      0.75     40000
weighted avg       0.77      0.77      0.77     40000



In [ ]:
import keras
from keras.layers import LSTM, Bidirectional, TimeDistributed, Conv1D, MaxPooling1D, BatchNormalization, Flatten

model = keras.models.Sequential()
# define CNN model
model.add(Conv1D(64, 2, activation='relu', padding='same', input_shape=(9,10)))
model.add(Conv1D(128, 2, activation='relu', padding='same'))
model.add(BatchNormalization())
model.add(MaxPooling1D())
model.add(Flatten())
# model.add(TimeDistributed(Flatten()))
# define LSTM model
# model.add(Bidirectional(LSTM(128, return_sequences=True),
#                              input_shape=(X_train.shape[1:])))
# model.add(Attention(units=128))
# model.add(keras.layers.Dropout(0.2))
# model.add(keras.layers.LSTM(128))
# model.add(Bidirectional(LSTM(128)))
model.add(keras.layers.Dense(64, activation='relu'))
model.add(keras.layers.Dropout(0.2))
# model.add(keras.layers.Dense(32, activation='relu'))
# model.add(keras.layers.Dropout(0.2))
model.add(keras.layers.Dense(7, activation='softmax'))
#Compiling the model
model.compile( loss='sparse_categorical_crossentropy', optimizer = keras.optimizers.Adam(learning_rate=0.001, decay=1e-6), metrics=['accuracy'] )
# model.summary()

In [ ]:
import tensorflow as tf
callback = tf.keras.callbacks.EarlyStopping(monitor='val_accuracy', patience=20, mode = 'max', verbose = 1)
history = model.fit(X_train, y_train, epochs=10, validation_data=(X_test, y_test), callbacks=[callback])

Epoch 1/10
5000/5000 [==============================] - 19s 4ms/step - loss: 1.0725 - accuracy: 0.5985 - val_loss: 0.8894 - val_accuracy: 0.6679
Epoch 2/10
5000/5000 [==============================] - 19s 4ms/step - loss: 0.9003 - accuracy: 0.6587 - val_loss: 0.8242 - val_accuracy: 0.6856
Epoch 3/10
5000/5000 [==============================] - 21s 4ms/step - loss: 0.8465 - accuracy: 0.6761 - val_loss: 0.8167 - val_accuracy: 0.6929
Epoch 4/10
5000/5000 [==============================] - 17s 3ms/step - loss: 0.8125 - accuracy: 0.6891 - val_loss: 0.7682 - val_accuracy: 0.7085
Epoch 5/10
5000/5000 [==============================] - 17s 3ms/step - loss: 0.7915 - accuracy: 0.6962 - val_loss: 0.7622 - val_accuracy: 0.7101
Epoch 6/10
5000/5000 [==============================] - 17s 3ms/step - loss: 0.7740 - accuracy: 0.7025 - val_loss: 0.7463 - val_accuracy: 0.7150
Epoch 7/10
5000/5000 [==============================] - 18s 4ms/step - loss: 0.7611 - accuracy: 0.7063 - val_loss: 0.7313 - val_ac

In [ ]:
aa = model.predict(X_test)
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
y_pred = np.argmax(aa, axis=1)
print(classification_report(y_test,y_pred))

1250/1250 [==============================] - 2s 2ms/step
              precision    recall  f1-score   support

           0       0.86      0.97      0.91      9136
           1       0.73      0.74      0.73      6083
           2       0.88      0.71      0.79      7665
           3       0.49      0.67      0.57      5915
           4       0.51      0.34      0.41      4187
           5       0.71      0.68      0.70      5250
           6       0.92      0.73      0.82      1764

    accuracy                           0.73     40000
   macro avg       0.73      0.69      0.70     40000
weighted avg       0.74      0.73      0.72     40000

